# Generated by Django 4.2.2 on 2023-07-02 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pyment_delivery', 'Payment delivery'), ('pickup_from_seller', 'Pickup from seller'), ('pickup_from_other_location', 'Pickup from other location'), ('free_delivery', 'Free delivery'), ('other', 'Other')], db_column='method', max_length=128)),
            ],
            options={
                'db_table': 'delivery_method',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Sweater', 'sweater'), ('Jacket', 'jacket'), ('Pants', 'pants'), ('Vest', 'vest'), ('Coat', 'coat'), ('Dress', 'dress'), ('Jeans', 'jeans'), ('Shirt', 'shirt'), ('Shorts', 'shorts'), ('Swimsuit', 'swimsuit'), ('Skirt', 'skirt'), ('Sock', 'sock'), ('Pajamas', 'pajamas'), ('Cardigan', 'cardigan'), ('suit', 'Suit'), ('Raincoat', 'raincoat'), ('sleeveless_shirt', 'Sleeveless shirt'), ('Belt', 'belt'), ('other', 'Other')], db_column='item type', max_length=256)),
                ('colors', models.CharField(db_column='colors', max_length=128)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserDeliveryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.deliverymethods')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_delivery_method',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items_interest',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(db_column='condition', max_length=128)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.item')),
            ],
            options={
                'db_table': 'item_condition',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.itemcondition'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
