# Generated by Django 4.2.2 on 2023-07-13 18:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsraeliAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['city', 'district', 'postal_code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', default='none', max_length=256, validators=[django.core.validators.MinLengthValidator(4)])),
                ('item_type', models.CharField(choices=[('sweater', 'Sweater'), ('jacket', 'Jacket'), ('pants', 'Pants'), ('vest', 'Vest'), ('coat', 'Coat'), ('dress', 'Dress'), ('jeans', 'Jeans'), ('shirt', 'Shirt'), ('shorts', 'Shorts'), ('swimsuit', 'Swimsuit'), ('skirt', 'Skirt'), ('sock', 'Sock'), ('pajamas', 'Pajamas'), ('cardigan', 'Cardigan'), ('suit', 'Suit'), ('raincoat', 'Raincoat'), ('sleeveless_shirt', 'Sleeveless shirt'), ('belt', 'Belt'), ('other', 'Other')], db_column='item_type', max_length=256)),
                ('colors', models.CharField(db_column='colors', max_length=128)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('item_condition', models.CharField(blank=True, choices=[('as new', 'As New'), ('used', 'Used'), ('Needed repair', 'needed_repair'), ('In box', 'in_box')], db_column='item_condition', max_length=256, null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, default=0, max_digits=5, null=True)),
                ('is_free', models.BooleanField(db_column='is free', default=False)),
                ('delivery_method', models.CharField(blank=True, choices=[('pyment_delivery', 'Payment delivery'), ('pickup_from_seller', 'Pickup from seller'), ('pickup_from_other_location', 'Pickup from other location'), ('free_delivery', 'Free delivery'), ('other', 'Other')], db_column='delivery_method', max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(db_column='rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review_text', models.TextField(blank=True, db_column='review_text', null=True)),
                ('created_at', models.DateField(auto_now_add=True, db_column='created_at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.item')),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_set', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ItemInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items_interest',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes_app.israeliaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
