# Generated by Django 4.2.2 on 2023-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='israeliaddress',
            table='address',
        ),
    ]
