# Generated by Django 4.2.2 on 2023-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0002_alter_israeliaddress_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='israeliaddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
