# Generated by Django 4.2.2 on 2023-07-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes_app', '0004_review_review_date_alter_customerdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_dateils', to=settings.AUTH_USER_MODEL),
        ),
    ]
