# Generated by Django 4.2.2 on 2023-07-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0005_alter_customerdetails_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='customerdetails',
            table='customer_dateils',
        ),
    ]
