# Generated by Django 4.2.2 on 2023-07-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0006_alter_customerdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clothes_app.israeliaddress'),
        ),
    ]
