# Generated by Django 4.2.2 on 2023-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0007_alter_customerdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='israeliaddress',
            name='city',
            field=models.CharField(default='nune', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='israeliaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
