# Generated by Django 4.2.2 on 2023-07-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes_app', '0008_alter_israeliaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_details', to='clothes_app.israeliaddress'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
