# Generated by Django 4.2.2 on 2023-07-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0009_alter_customerdetails_address_alter_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='clothes_app.israeliaddress'),
        ),
    ]
