# Generated by Django 4.2.2 on 2023-08-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0011_customerdetails_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('sweater', 'Sweater'), ('jacket', 'Jacket'), ('pants', 'Pants'), ('vest', 'Vest'), ('coat', 'Coat'), ('dress', 'Dress'), ('jeans', 'Jeans'), ('shirt', 'Shirt'), ('shorts', 'Shorts'), ('swimsuit', 'Swimsuit'), ('skirt', 'Skirt'), ('sock', 'Sock'), ('pajamas', 'Pajamas'), ('cardigan', 'Cardigan'), ('suit', 'Suit'), ('raincoat', 'Raincoat'), ('sleeveless shirt', 'Sleeveless shirt'), ('belt', 'Belt'), ('other', 'Other')], db_column='item_type', max_length=256),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1024, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_img', to='clothes_app.item')),
            ],
            options={
                'db_table': 'item_img',
                'ordering': ['id'],
            },
        ),
    ]
