# Generated by Django 4.2.2 on 2023-09-10 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes_app', '0012_alter_item_item_type_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_dateils', to=settings.AUTH_USER_MODEL),
        ),
    ]
