# Generated by Django 4.2.2 on 2023-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0013_alter_customerdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Sweater', 'sweater'), ('jacket', 'Jacket'), ('pants', 'Pants'), ('vest', 'Vest'), ('coat', 'Coat'), ('dress', 'Dress'), ('jeans', 'Jeans'), ('shirt', 'Shirt'), ('shorts', 'Shorts'), ('swimsuit', 'Swimsuit'), ('skirt', 'Skirt'), ('sock', 'Sock'), ('pajamas', 'Pajamas'), ('cardigan', 'Cardigan'), ('suit', 'Suit'), ('raincoat', 'Raincoat'), ('sleeveless shirt', 'Sleeveless shirt'), ('belt', 'Belt'), ('other', 'Other')], db_column='item_type', max_length=256),
        ),
    ]
