# Generated by Django 4.2.2 on 2023-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0014_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery_method',
            field=models.CharField(blank=True, db_column='delivery_method', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_condition',
            field=models.CharField(blank=True, db_column='item_condition', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(db_column='item_type', max_length=256),
        ),
    ]
