# Generated by Django 4.2.2 on 2023-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0015_alter_item_delivery_method_alter_item_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='phone_number',
            field=models.CharField(unique=True),
        ),
    ]
